# -*- coding: utf-8 -*-
"""DataFrame

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fVqbG7WXXLfGMM1C_14C3jgR1eX8jDLa
"""

import pandas as pd
import numpy as np

data = {'Compuesto Químico': ['Cafeína', 'Trigonelina', 'Ácido clorogénico', 'Ácido cafeico', 'Quinic acid', 'Ácido ferúlico', 'Ácido málico', 'Ácido cítrico', 'Diterpenoides', 'Putrescina', '5-Hidroximetilfurfural', 'Ácido acético', 'Fenol', 'Furano', 'Ácido linoleico', 'Ácido palmítico', 'Ácido esteárico', 'Ácido láctico', 'Metilxantina', 'Acetaldehído', 'Propanol', 'Teobromina', 'Glucosa', 'Sacarosa', 'Ácido fórmico'],
        'Señales RMN (13C) (ppm)': [155.4, 143.6, 174.0, 126.9, 74.2, 148.4, 68.3, 177.2, 40.0, 40.8, 177.0, 181.5, 150.5, 110.2, 130.2, 34.0, 34.1, 70.3, 150.3, 203.5, 67.0, 155.3, 96.1, 105.3, 160.5],
        'Señales RMN (1H) (ppm)': [3.36, 8.10, 6.45, 7.56, 4.25, 7.61, 4.00, 2.63, 1.17, 2.76, 9.50, 11.50, 6.98, 7.26, 5.38, 2.34, 2.34, 4.18, 7.80, 9.80, 1.75, 3.55, 3.75, 5.45, 8.02]}

df = pd.DataFrame(data)
print(df)

print(df['Compuesto Químico'])

#1

df['Category'] = df['Señales RMN (1H) (ppm)'].apply(lambda x: 'Alto' if x >= 5.4 else 'Bajo')

print(df.loc[df['Category'] == 'Alto'])

#2

Bajo = df[df['Señales RMN (1H) (ppm)'] < 5.4]
print(Bajo)

#3

df['Estructura'] = ['C8H10N4O2', 'C7H7NO2', 'C16H18O9', 'C9H8O4', 'C7H12O6', 'C10H10O4', 'C4H6O5', 'C6H8O7', 'C20H30O', 'C4H12N2', 'C6H6O3', 'CH3COOH', 'C6H5OH', 'C4H4O', 'C18H32O2', 'C16H32O2', 'C18H36O2', 'C3H6O3', 'C7H8N4O2', 'C2H4O', 'CH3CH2CH2OH', 'C7H8N4O2', 'C6H12O6', 'C12H22O11', 'CH2O2']
print(df)

#4

df = df.drop('Señales RMN (13C) (ppm)', axis=1)
print(df)

#5

grouped = df.groupby('Señales RMN (1H) (ppm)')['Category'].agg(lambda x: x.mode()[0])
print(grouped)

#6

df_sorted = df.sort_values(by='Señales RMN (1H) (ppm)', ascending=True)
print(df_sorted)

#7

df.rename(columns={'Compuesto Químico': 'Moleculas Cafe', 'Estructura': 'Fórmula molecular'}, inplace=True)
print(df)

#8

df['Señales RMN (1H) (ppm)'] = df['Señales RMN (1H) (ppm)'].astype(float)
print(df.dtypes)

#9

print(df[df['Moleculas Cafe'] == 'Cafeína'])

#10